project_name: vesurvius-challenge
exp_name: deform-dynunet-k${kernel_size}-s${sigma}-160-patch-with-augs
data_path: ./data/vesuvius-challenge-surface-detection
oof_path : ./data/nnunet_oof/oof
oof_path2: ''
nnunet_path: ./nnunet
petrained_ckpt_path: ''
data_split_path: ./splits.json
batch_size: 1
num_workers: 4
lr: 1e-3
offline: true
fold_id: 0
n_splits: 5
seed: 42
input_size: [160, 160, 160]
threshold: 0.5
selected_fold: 0
is_prob_oof_mask: false
apply_gaussian: true

#model config
use_resenc: true
max_v: 3.0 #Max instantaneous displacement ≈ v voxels
n_steps: 5
lambda_jac: 1.0
lambda_smooth: 0.1
lambda_ce: 1
lambda_dice: 1
alpha: 0.3
beta: 0.7
kernel_size: 3
sigma: 10


defaults:
  - models: deform_dynunet
  - optimizers: AdamW
  - data: data_deform
  - trainer: deformSegTrainer
  - _self_


