project_name: vesurvius-challenge
exp_name: deform-dynunet
data_path: ./data/vesuvius-challenge-surface-detection
nnunet_path: ./nnunet
petrained_ckpt_path: ''
batch_size: 1
num_workers: 4
lr: 1e-2
offline: true
fold_id: 0
n_splits: 5
seed: 42
threshold: 0.5

#model config
max_steps: 3
initial_step: 0
latent_dim: 128
base_channels: 256
beta_kl: 10.0
recon_loss: "l1"
alpha_ramp_iters: 8000
phase_iters: 8000
use_epoch_phase: False
max_epochs_per_step: null
recon_target: "mask"
init_res: 32


defaults:
  - models: cvae3d
  - optimizers: AdamW
  - data: data_cvae3d
  - trainer: trainer_cvae3d
  - _self_


