
project_name: 'vesurvius-challenge'
exp_name: 'dynunet'
batch_size: 2
num_workers: 12
image_size: ${input_size}
input_size: [128, 128, 128]
vol_size: [128, 320, 320]

defaults:
  - models: dynunet
  - optimizers: AdamW
  - trainer: dynunet
  - _self_


transforms:
  train:
    - EnsureChannelFirstd:
        keys: [ "Image", "Mask" ]
        channel_dim: "no_channel"
    - EnsureTyped:
        keys: [ "Image", "Mask" ]
    - Resized:
        keys: [ "Image", "Mask" ]
        spatial_size: ${vol_size}
        mode: [ "trilinear", "nearest" ]
    - PosNegSampled:
        keys: [ "Image", "Mask" ]
        label_key: "Mask"
        spatial_size: ${input_size}
        pos: 6
        neg: 4
        image_key: "Image"
        num_samples: 10
        allow_smaller: True
        rand_state: None
    - ScaleIntensityd:
        keys: [ "Image" ]
        minv: 0
        maxv: 1
    - SpatialPadd:
        keys: [ "Image", "Mask" ]
        spatial_size: ${input_size}
        mode: "constant"
        method: "symmetric"
    - ConcatItemsd:
        keys: [ "Image", "Mask" ]
        name: [ "Image", "Mask" ]
        dim: 0
    - ToTensord:
        keys: [ "Image", "Mask" ]

  val:
    - EnsureChannelFirstd:
        keys: ["Image", "Mask"]
        channel_dim: "no_channel"
    - EnsureTyped:
        keys: ["Image", "Mask"]
    - Resized:
        keys: ["Image", "Mask"]
        spatial_size: ${vol_size}
        mode: ["trilinear", "nearest"]
    - ScaleIntensityRangePercentilesd:
        keys: ["Image"]
        lower: 2
        upper: 98
        b_min: 0
        b_max: 1
    - ToTensord:
        keys: ["Image", "Mask"]
