project_name: 'vesurvius-challenge-stage-1'
exp_name: 'dynunet'
data_path: './data/vesuvius-challenge-surface-detection'
batch_size: 2
num_workers: 12

defaults:
  - models: dynunet
  - optimizers: AdamW
  - trainer: dynunet
  - data: data
  - _self_
