project_name: vesurvius-challenge
exp_name: IC-Deformnet-k${kernel_size}-s${sigma}-full-depth-rand-thr-aug
data_path: ./data/vesuvius-challenge-surface-detection
oof_path : ./data/prob_predictions
oof_path2: ''
nnunet_path: ./nnunet
petrained_ckpt_path: ''
data_split_path: ./splits.json
batch_size: 1
num_workers: 4
lr: 1e-3
offline: true
fold_id: 0
n_splits: 5
seed: 42
input_size: [-1, 128, 128]
threshold: 0.5
selected_fold: 0
is_prob_oof_mask: true
apply_gaussian: true

#model config
use_resenc: true
lambda_jac: 1.0
lambda_smooth_ic: 0.05
lambda_iter: 0.1   # optional, start at 0
num_iters: 3
max_delta_v: 0.5
kernel_size: 3
sigma: 10


defaults:
  - models: deform_dynunet
  - optimizers: AdamW
  - data: data_deform
  - trainer: deformSegTrainer
  - _self_


