project_name: 'vesurvius-challenge-stage-1'
exp_name: 'dynunet'
data_path: './data/vesuvius-challenge-surface-detection/data'
batch_size: 2
stage: 1

dataloader:
  _target_: "torch.utils.data.DataLoader"
  _partial_: True
  num_workers: 12
  prefetch_factor: 3
  batch_size: ${batch_size}
  pin_memory: True
  persistent_workers: True
  shuffle: True

defaults:
  - models: dynunet
  - optimizers: AdamW
  - trainer: dynunet
  - data: data
  - _self_
