project_name: vesurvius-challenge
exp_name: compose-dynunet-single-oof-patch-128
data_path: ./data/vesuvius-challenge-surface-detection
compose_label_path: ./data/train_compose_labels
oof_path1 : ./nnunet/nnUNet_results/Dataset900_VesuviusScroll/nnUNetTrainer__nnUNetResEncUNetMPlans__3d_fullres/oof_deform_gaussian/oof
oof_path2: ''
oof_path3: ''
nnunet_path: ./nnunet
petrained_ckpt_path: ./models/last-v1.ckpt
data_split_path: ./splits_final.json
batch_size: 1
num_workers: 4
lr: 1e-3
offline: true
fold_id: 0
n_splits: 5
seed: 42
input_size: [128, 128, 128]
threshold: 0.5
selected_fold: ''
is_prob_oof_mask: false
apply_gaussian: true

#model config
lambda_sdf: 1.0
lambda_thickness: 1.0
lambda_normals: 1.0

#model structures
n_blocks: 3
kernel_size: 3
sigma: 5


defaults:
  - models: composeNet
  - optimizers: AdamW
  - data: data_compose
  - trainer: composeNetTrainer
  - _self_