project_name: vesurvius-challenge
exp_name: cdl-dynunet
data_path: ./data/vesuvius-challenge-surface-detection
cdl_label_path: ./data/train_cdl_labels
dictionary_path: ./data/train_cdl_labels
nnunet_path: ./nnunet
petrained_ckpt_path: ''
data_split_path: ./splits_final.json
batch_size: 1
num_workers: 4
lr: 1e-3
offline: true
fold_id: 0
n_splits: 5
seed: 42
input_size: [-1, 128, 128]
threshold: 0.5
selected_fold: ''

#model config
lambda_sparse: 1.0


defaults:
  - models: composeCDL
  - optimizers: AdamW
  - data: data_CDL
  - trainer: composeCDLTrainer
  - _self_